name: Github actions
on:
  push:
    branches: [ main ]

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Show files in repo
        run: ls -a

      - name: Log into Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME}}/devops .

      - name: Push Docker image to docker hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/devops:latest



